# Generated by Django 5.0.6 on 2026-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alumni_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm.'), ('EEE', 'Electrical & Electronics'), ('Mech', 'Mechanical'), ('Civil', 'Civil'), ('MBA', 'MBA'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm.'), ('EEE', 'Electrical & Electronics'), ('Mech', 'Mechanical'), ('Civil', 'Civil'), ('MBA', 'MBA'), ('Other', 'Other')], max_length=20),
        ),
    ]
