# Generated by Django 5.0.6 on 2026-07-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_alumni_branch_alter_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
    ]
