# Generated by Django 5.0.6 on 2026-07-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alumnisubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='photo',
            field=models.TextField(blank=True, help_text='Profile photo (data URL)'),
        ),
    ]
