# Generated by Django 5.0.6 on 2026-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alumni_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnisubmission',
            name='photo',
            field=models.TextField(blank=True, help_text='Profile photo (data URL)'),
        ),
    ]
